"""Add admin_review_requested to Enrollment

Revision ID: 2bd4bec4a077
Revises: b7e9c3d1f2a8
Create Date: 2026-05-03 19:31:18.788841

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '2bd4bec4a077'
down_revision = 'b7e9c3d1f2a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('admin_review_requested', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'admin_review_requested')
    # ### end Alembic commands ###

