"""add avatar_url to user

Revision ID: 9468bbf70a49
Revises: 2bd4bec4a077
Create Date: 2026-05-03 19:54:37.970609

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '9468bbf70a49'
down_revision = '2bd4bec4a077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###

